spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hopon
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ride-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.kiran.hop_on.model"
  redis:
    host: localhost
    port: 6379

jwt:
  secret: A3sR7!kG2@hN9%qXxL#zYc$W8MpUeRbF


server:
  port: 8080
