spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hopon
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
#  redis:
#    host: localhost
#    port: 6379

server:
  port: 8080
